### ISSUE TITLE
Overeenkomsten websites

### ISSUE THREAD

**Issue by tkon99** [Vogeltak/magister-email#2]
Hi Vogeltak,

Zoals je misschien weet ben ik betrokken bij simplyHomework, een slimme huiswerkplanner. Zie http://simplyHomework.nl

Nu is het zo dat jouw "logo" (naam) sterk lijkt op onze stijl. Ik weet niet of dit toevallig is en verwijt je ook niets. (Daarentegen: bedankt voor je mooie python library). Maar zou je dit even kunnen fixen.

Alvast bedankt,

Thomas

**Comment by Vogeltak** [comment]
Hoi Thomas,

Van simplyHomework en jouw betrekking daarbij ben ik inderdaad op de hoogte.
Ik vind het interessant dat je over plagiaat begint in dit geval. Bij de creatie van dit project en de loginpagina was ik niet op de hoogte van jullie siteheader. Ik heb echter niets van jullie werk gekopieerd en het gebruikt als mijn creëren. Naar mijn weten is het dus geen plagiaat. Wat betreft de redelijk overeenkomende stijlen van onze twee siteheaders, dat gebeurt. Worden alle sites die #000 arial als header stijl gebruiken ook beschuldigd van plagiaat door een grote commerciële speler die toevallig diezelfde stijl gebruikt voor zijn website? Neen.

Ik ben dus van mening dat het in dit geval geen plagiaat betreft. Mocht je nog verdere zwaarwegende argumenten hebben, laat het me dan weten.

~Vogeltak

**Comment by tkon99** [comment]
Hi vogeltak,

Sorry voor de benaming "plagiaat". Het gaat enkel om een verzoek tot aanpassing, ik kan je niets verplichten maar zou het fijn vinden als je het aan zou passen.

Je kunt overeenkomsten niet ontkennen:
<img src="http://i.imgur.com/VRVWVWK.png">
*Hebben we intern laten rond gaan vandaar "zijn" en "onze"*

Het gaat me echt puur om de vorm van de header. Met bold en gewoon naast elkaar in het wit, aan elkaar en met een hoofdletter in het midden.
Blauwe achtergrond boeit me niets (dat hebben nogal wat website :stuck_out_tongue_winking_eye: )

Het is je eigen beslissing maar je kunt niet rekenen op onze steun bij je projecten als je het niet aanpast.

Groeten,

Thomas

**Comment by Vogeltak** [comment]
Hoi Thomas,

Mijn excuses voor het redelijk agressieve antwoord dat ik gegeven heb (ik lees het nu zo terug en zie dat ik toch wat grof ben geweest. Opnieuw, mijn excuses hiervoor). Het is nooit mijn bedoeling geweest jullie of wie dan ook tegen de borst te stuiten met mijn projecten. Als je echt zoveel waarde hecht aan de integriteit van je header stijl, ben ik natuurlijk bereid om de stijl aan te passen. Ik zal er zo snel mogelijk iets aan doen.

Het klinkt alsof jullie team redelijk groot is door "..intern laten rond gaan..". Zijn jullie flink gegroeid sinds jij en Lieuwe begonnen?

~Vogeltak

**Comment by tkon99** [comment]
Hi vogeltak,

Haha, dacht al. Wel raar en zakelijk antwoord. (Niet van je gewend).
Maakt niet uit... ik zette ook redelijk hoog in.

We zijn nu met z'n drieën. [Tom Smeding](https://github.com/tomsmeding) maakt voor ons het huiswerk plan gedeelte (o.a. zelflerende algoritmes).
Ik hecht er met name waarde aan omdat de header (na het logo) het eerste is dat mensen zien op onze website (zo niet eerder). Het is dus een groot deel van onze identiteit.

We hebben trouwens veel contacten opgebouwd de laatste maanden en zijn van plan om medio augustus te lanceren. Dus ja. Het gaat wel snel nu.

Mocht je hulp willen bij het aanpassen dan helpen we natuurlijk graag!

Thomas

**Comment by Vogeltak** [comment]
H Thomas,

Zakelijk schrijven vind ik af en toe best puik. Aangezien je dan veelal logische en rationele regels toepast.

Ik ben zeer benieuwd hoe jullie simplyHomework de komende maanden zullen ontwikkelen. Ik las laatst trouwens een interessante blogpost over [de belabberdheid van freemium en hoe cheapium beter werkt](http://jaredbrown.me/post/6071815182/freemium-is-a-money-burning-business-model). Een interessant gegeven om eens over na te denken.

Mocht je het nog niet gezien hebben, de header style heb ik aangepast. Ik zal zo even een nieuwe screengrab uploaden.

~http://jaredbrown.me/post/6071815182/freemium-is-a-money-burning-business-model
